### ISSUE TITLE
TypeError: Cannot read property 'uri' of null

### ISSUE THREAD

**Issue by ghost** [neoclide/coc-python#9] opened 2019-03-27 11:15 UTC
Hi!

After installing coc-python, i open python file and get a error message like in title of this issue.

![2019-03-27-121333_1680x1050_scrot](https://user-images.githubusercontent.com/48855491/55071856-fb65b880-5089-11e9-812d-9da22665d655.png)

**Comment by chemzqm** [comment] 2019-03-27 11:40
You need to create file before open it, this is how VSCode works, but not vim.

**Comment by chemzqm** [comment] 2019-03-27 14:16
Duplicate of #6 .

**Closed by chemzqm** 2019-03-27 14:16 UTC
Labels: bug
