### ISSUE TITLE
Python completion error

### ISSUE THREAD

**Issue by surmish** [neoclide/coc-python#179] opened 2020-04-19 20:03 UTC
## Describe the bug

```
[coc.nvim] Jedi error: Traceback (most recent call last):                                                                               
  File "completion.py", line 624, in watch                                                                                              
    response = self._process_request(rq)                                                                                                
  File "completion.py", line 574, in _process_request                                                                                   
    sys_path=sys.path, environment=self.environment)                                                                                    
  File "/home/ubuntu/.local/lib/python3.7/site-packages/jedi/api/__init__.py", line 133, in __init__                                    
    project._sys_path = sys_path 
```

The python code in jedi `__init__.py` has the following:

``` Python
def __init__(self, code=None, line=None, column=None, path=None,
               encoding=None, sys_path=None, environment=None,                                                                        
               project=None, source=None):
```
This function is being called with the default project argument from CoC (completion.py) which causes the error.

It looks like the deprecated section of the code is being triggered in 
`~/.local/lib/python3.7/site-packages/jedi/api/__init__.py` line 133

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**
The vimrc simply contains the coc.nvim plugin. I am running a small python script 

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by rwendt-bw** [comment] 2020-04-20 20:43
I'm having the same issue. 

```
[coc.nvim] Jedi error: Traceback (most recent call last):                                                                                                                            
  File "completion.py", line 624, in watch
    response = self._process_request(rq)
  File "completion.py", line 574, in _process_request
    sys_path=sys.path, environment=self.environment)
  File "/home/rwendt/.local/lib/python3.7/site-packages/jedi/api/__init__.py", line 133, in __init__
    project._sys_path = sys_path
AttributeError: 'NoneType' object has no attribute '_sys_path'
```
with this mini.vim

```
set nocompatible
set runtimepath^=/home/rwendt/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```
I notice the error happens whenever I make a class definition or function
![Screenshot from 2020-04-20 16-41-17](https://user-images.githubusercontent.com/42274154/79797793-e196b380-8325-11ea-91f1-b38251a08286.png)

**Comment by rwendt-bw** [comment] 2020-04-20 20:46
Sorry looks like this is a duplicate of #175 
Downgrading to 0.16.0 fixes the error

**Comment by hovnatan** [comment] 2020-04-21 10:23
I have the same issue with jedi 0.17.0. Downgrading to 0.16.0 fixes the issue.

**Comment by jesperrix** [comment] 2020-04-22 08:10
This is fixed with https://github.com/neoclide/coc-python/pull/180 i believe

**Comment by her** [comment] 2020-04-22 22:24
I need this fix :( How can I pull this into `coc-python` ? Looks like I have the latest release `1.2.9` from Feb. @chemzqm Are you going to make a release for this?

**Comment by orestisfl** [comment] 2020-04-23 06:23
You could just apply the patch locally in `~/.config/coc/extensions/node_modules/coc-python/pythonFiles/completion.py`

**Comment by chemzqm** [comment] 2020-04-23 08:21
Many changes need made to work well with latest jedi, I found the file in vscode-python doesn't work as well.

**Closed** 2020-04-23 14:56 UTC
Labels: bug

**Comment by her** [comment] 2020-04-23 17:19
Cool, thanks guys!

**Comment by theonlygusti** [comment] 2020-10-18 13:51
Are we required to `pip install jedi` in every single virtualenv we create on our computer just to use coc-python with jedi?
