### ISSUE TITLE
'Error output from python: Unable to find document' for files without extension

### ISSUE THREAD

**Issue by oblitum** [neoclide/coc-python#5] opened 2019-03-27 00:48 UTC
Getting `[coc.nvim] Error output from python: Unable to find document file:///home/me/foo` for python files with shebang but without extension (`foo` file causes error, `foo.py` doesn't).

**Comment by chemzqm** [comment] 2019-03-27 14:25
The problem is when you edit file in home directory, the workspaceFolder of coc is undefined.

**Comment by oblitum** [comment] 2019-03-27 15:05
Sorry the confusion, my cwd was not home actually, it was `/home/me/something/`.

**Comment by oblitum** [comment] 2019-03-27 15:06
The same file was causing error just by renaming and removing extension.

**Comment by chemzqm** [comment] 2019-03-27 19:40
I've changed coc-python use jedi by default, duplicate of #10.

**Closed by chemzqm** 2019-03-27 19:40 UTC
Labels: bug
